from pathlib import Path

class TestReporter:

    def __init__(self):
        self.results = []
        self.report_path = Path(__file__).resolve().parent.parent / "test_report.md"

    def record_result(self, test_name, total_time : float , status, image_name, details, regression_warning):
        """
        Records the outcome of a single test.
        """
        # We store these as a dictionary so it is easy to read later
        self.results.append({
            "test_name": test_name,
            "total_time": total_time,
            "status": status,
            "image_name": image_name,
            "details": details,
            "regression_warning": regression_warning
        })

    def generate_markdown(self):
        """
               Iterates over the recorded results and builds a human-readable Markdown file.
               """
        total = len(self.results)
        passed = sum(1 for r in self.results if r["status"] == "PASS")
        failed = sum(1 for r in self.results if r["status"] == "FAIL")
        skipped = sum(1 for r in self.results if r["status"] in ["SKIPPED", "ERROR"])

        with open(self.report_path, "w", encoding="utf-8") as f:
            # Report Title
            f.write("# VLM Test Execution Report\n")
            f.write("This report was automatically generated by the testing framework.\n\n")

            # Summary Section
            f.write("## Summary\n\n")
            f.write(f"- **Total Tests Run:** {total}\n")
            f.write(f"- **Passed:** ✅ {passed}\n")
            f.write(f"- **Failed:** ❌ {failed}\n")

            if skipped > 0:
                f.write(f"- **Skipped / Errors:** ⏭️ {skipped}\n")
            f.write("\n---\n\n")

            # Detailed Results Section
            f.write("## Test Details\n\n")
            for r in self.results:
                emoji = "✅" if r["status"] == "PASS" else "❌" if r["status"] == "FAIL" else "⏭️"
                f.write(f"### {emoji} {r['test_name']} - **{r['status']}**\n")
                f.write(f" - **Total Time:** {r['total_time']:.2f} Seconds\n")
                f.write(f"- **Image:** `{r['image_name']}`\n")
                f.write(f"- **Details:** {r['details']}\n\n")
                f.write(f"- **Regression Warning:** {r['regression_warning']}\n\n")

